version: '3.8'

services:

  gui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - INFLUXDB_DATABASE=influx
      - INFLUXDB_HOST=10.0.2.15
      - INFLUXDB_PASSWORD=admin
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=admin
      - NS3_HOST=10.0.2.15

  grafana:
    image: grafana/grafana:8.0.2
    env_file: configuration.env
    ports:
      - '3000:3000'
    command: sh -c "echo \"1,2,3\" > provacsv.csv"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
volumes:
  grafana_data: {}
